### PR TITLE
Open location from Android intent with geo: url

### PR DESCRIPTION
**Pull request by starsep**
Draft Android implementation of https://github.com/Zverik/every_door/issues/387

Currently it is still buggy:
- sometimes current geolocation is opened, not the one shared from another app
- sometimes previous shared geolocation is opened

Please let me know if such an approach even makes sense.

I tried using https://pub.dev/packages/receive_sharing_intent but it wouldn't compile due Java version mismatch.

PS I don't really know Flutter so any advices are welcome :smile:

### CODE REVIEW

**Comment by Zverik** [comment]
Hmm, what's the problem with Java version? In the future ED will need to be a file target as well, so maybe `receive_sharing_intent` is still the way to go?

**Comment by starsep** [comment]
1. Add `receive_sharing_intent: ^1.8.0` to depencies in pubspec.yaml
2. Build project
3. Error:
```
Running Gradle task 'assembleDebug'...
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':receive_sharing_intent:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

**Comment by Zverik** [comment]
Your error is weird, because by [SO answers](https://stackoverflow.com/questions/70368175/why-am-i-getting-this-warning-and-how-to-resolve-it-this-version-only-understan), ED has enough version buffer to not have this.

I get another issue with the package:

```
Execution failed for task ':receive_sharing_intent:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

Seems like the package is unmaintained at the moment, judging by the number of pull requests hanging. Also, it doesn't seem to [support iOS 18](https://github.com/KasemJaffer/receive_sharing_intent/issues/324).

Maybe there's an alternative?..

What I don't like about the ad-hoc solution is that it doesn't support iOS. I'd prefer to have identical features for both OS-es.

**Comment by Zverik** [comment]
Closing in favor of #806. Thank you Filip for the nudge in this direction!

**Pull request closed without merging**
