### PR TITLE
feat: add button to view an elements history in browser

### LINKED ISSUE #233: [feature request] Easy way to access PoI history
Sometimes it is useful to be able to see the history of the amenity — for example if an amenity has become disused, it is helpful to be able to see what was previously there.

This could be as simple as another button at the top of the PoI view (highlighted in purple), that opens the browser at the osm.org history page for that PoI.

It could also be implemented natively, but I _doubt_ that history data is currently downloaded from the API, meaning you'd need to make a network request anyway.

### PR DESCRIPTION
**Pull request by GeorgeHoneywood**
Resolves #233.

https://user-images.githubusercontent.com/25514836/174190981-656da7f9-3e13-4746-8afd-932bf13c3496.mp4

Feel free to ignore this if you already had some implementation in mind. I'm not entirely sure about `launchHistoryPage()` being in the `OsmElement` class, but I can't think of anywhere better.

Using the `kOsmAuth2Endpoint` constant to get the base URL for the `openstreetmap.org` website is a bit janky. Using the API URL constant would also work, as there seems to be some sort of redirect -- so visiting `api.openstreetmap.org/way/x/history` gets a 301 pointing to `www.openstreetmap.org/way/x/history` -- but not sure we should rely on that behaviour.

Thanks!

### CODE REVIEW

**Comment by Zverik** [comment]
Thanks George, I'm happy you did a pull request :) There are few comments about it:
* The editor pane is not a good place to put the button: it requires internet connection, so it goes against the common assumption of an offline editor, and it opens a web browser (or a web view), which could cause unloading the editor and losing changes to the current amenity. I propose moving it to the tags panel (`tags.dart`).
* Please do not add UI dependencies to models. it's okay to have all the code in a single handler function.
* Why do you force `externalApplication` mode?

**Comment by GeorgeHoneywood** [comment]
Thanks for looking at this!

I moved the button to the `tags.dart` page, and got rid of the helper function from the model.

Without `LaunchMode.externalApplication`, it opens the page right in the app, without any controls to indicate that you are looking at some external page -- and the only way to get back to use the system back button. There is [a flutter plugin](https://pub.dev/packages/flutter_custom_tabs) that lets you use ["custom tabs"](https://developer.chrome.com/docs/android/custom-tabs/) (or their iOS equivalent). Would this be preferable?

**Comment by Zverik** [comment]
No, `externalApplication` is fine if you think that's right. Two more comments:

* Could you please keep the sharing button the last one? It's a common UI pattern to have it at the edge of the screen — check other apps you have.
* Do you think we could use a better website for an element history, e.g. one that highlights changes? Here are some tools I found:
  * [PeWu's OSM History Viewer](https://wiki.openstreetmap.org/wiki/OSM_History_Viewer_(by_PeWu))
  * [Mapki's Deep Diff](https://wiki.openstreetmap.org/wiki/Mapki%27s_Deep_Diff)
  * [OSM Visual History](https://aleung.github.io/osm-visual-history/)
  * [OSM Deep History](https://osmlab.github.io/osm-deep-history/)

**Comment by GeorgeHoneywood** [comment]
I've fixed the button order :)

Regarding which website would be best, in my use case I just want to see what tags have changed -- I'm not usually concerned about geometry changes when editing on the go:

* The osm.org history page is functional, although it doesn't highlight tag changes (or show geometry changes). It is "official", and likely to be more stable than the alternatives. Pages weigh about 300kb.
* [Mapki's Deep Diff](https://wiki.openstreetmap.org/wiki/Mapki%27s_Deep_Diff) looks good in terms of highlighting tag changes, but doesn't seem to be mobile friendly. Has impressively light pages, about 5kb.
* [OSM Visual History](https://aleung.github.io/osm-visual-history/) & [OSM Deep History](https://osmlab.github.io/osm-deep-history/) seem to be very similar. These do a good job of showing tag changes, but are a bit weird on mobile. Page weight is about 300kb.
* [PeWu's OSM History Viewer](https://pewu.github.io/osm-history/#/way/295552919) seems like the most powerful, and does a good job of showing both tag and geometry changes. The user interface is a bit cluttered though, and it has the heaviest pages, about 600kb.

Personally I'm in favour of osm.org, as I think it is what most people would expect.

Thanks again!

**Comment by Zverik** [comment]
Thanks for checking each of the services. I'm doubtful about the OSM website, because you can open it with the "share" button, and yeah, its functions leave much to be desired.

I like PeWu's page, but yeah, 600kb. Half of which is `angular.js`, which my browser seem to cache.  I guess we could do the default osm.org, and wait for a challenger to appear.

**Pull request merged**
