### PR TITLE
[android] Add an adaptive icon version

### PR DESCRIPTION
**Pull request by RedAuburn**
Reworked & cleaned up the original icon SVG as it was broken, added a new adaptive icon version for Android 13's Adaptive icons:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

also removed the unused and legacy `ic_launcher_round` files

### CODE REVIEW

**Comment by RedAuburn** [comment]
hmm, it's added a border around the raster icons. Hang on.

**Comment by RedAuburn** [comment]
Worked around it, should be good now

**Comment by Zverik** [comment]
Awesome work, thank you Harry! I plan to release a new version this month, so I'll check this out soon :)

**Comment by RedAuburn** [comment]
> Awesome work, thank you Harry! I plan to release a new version this month, so I'll check this out soon :)

Cool! Thank you for every door in the first place, it's very useful :)

**Pull request merged**
